@startuml
package modelo {
    class Usuario_registrado {
        - nombre: String
        - usuario: String
        - contraseña: String
        - rutinas: ArrayList<Rutina>

        + Usuario_registrado(nombre: String, usuario: String, contraseña: String, rutinas: ArrayList<Rutina>)
        + getNombre(): String
        + setNombre(nombre: String): void
        + getUsuario(): String
        + setUsuario(usuario: String): void
        + getContraseña(): String
        + setContraseña(contraseña: String): void
        + getRutinas(): ArrayList<Rutina>
        + setRutinas(rutinas: ArrayList<Rutina>): void
        + verEjercicios(rutina: Rutina): ArrayList<Ejercicio>
    }

    class Rutina {
        - ID: int
        - ejercicios: ArrayList<Ejercicio>

        + Rutina(ID: int, ejercicios: ArrayList<Ejercicio>)
        + getID(): int
        + setID(ID: int): void
        + getEjercicios(): ArrayList<Ejercicio>
        + setEjercicios(ejercicios: ArrayList<Ejercicio>): void
        + añadirEjercicioRutina(ejercicio: Ejercicio): void
        + eliminarEjercicioRutina(ejercicio: Ejercicio): void
    }

    class Ejercicio {
        - nombre: String
        - seccion: String
        - musculo: String

        + Ejercicio(nombre: String, musculo: String, seccion: String)
        + getNombre(): String
        + setNombre(nombre: String): void
        + getSeccion(): String
        + setSeccion(seccion: String): void
        + getMusculo(): String
        + setMusculo(musculo: String): void
        + toString(): String
    }

    class Gestor {
        - url: String
        - usuario: String
        - contraseña: String
        - conexion: Connection
        - consulta: Statement

        + Gestor()
        + desconectar(): void
        + comprobarUsuario(usuario: String): boolean
        + insertarUsuario(nombre: String, usuario: String, contraseña: String): boolean
        + comprobarUsuarioConClave(usuario: String, contraseña: String): boolean
        + obtenerEjercicios(): ArrayList<Ejercicio>
        + seleccionarUsuario(usuario: String): Usuario_registrado
        + cambiarNombre(usuario: String, nuevoNombre: String): boolean
        + cambiarUsuario(usuario: String, nuevoUsuario: String): boolean
        + cambiarContraseña(usuario: String, nuevaClave: String): boolean
        + rutinas(usuario: String): ArrayList<Rutina>
        + ejercicios(id: int): ArrayList<Ejercicio>
        + agregarRutina(usuario: String): boolean
        + eliminarRutina(id: int): boolean
        + agregarEjercicio(id: int, ejercicio: String, musculo: String): boolean
        + obtenerMusculos(): ArrayList<String>
        + obtenerEjerciciosPorMusculo(musculoSeleccionado: String): ArrayList<Ejercicio>
        + eliminarEjercicio(id: int, nombreEjercicio: String): boolean
    }
}

package gui {
    class VentanaPrincipal extends JFrame {
        - serialVersionUID: long

        + VentanaPrincipal()
        - crearVentana(): void
    }

    class EstructuraPanel extends JPanel {
        - serialVersionUID: long
        - header: JPanel
        - footer: JPanel
        - panelActual: JPanel

        + EstructuraPanel()
        - crearFooter(): void
        - crearHeader(): void
        - crearPanel(): void
    }

    class Menu extends EstructuraPanel {
        - serialVersionUID: long

        + Menu()
        - cargarContenido(): void
        - cargarImagen(): void
        - cargarBotonGestionarDatos(): void
        - cargarBotonGestionarRutinas(): void
        - cargarBotonEjercicios(): void
        - cargarContenidoHeader(): void
        - cargarBotonInicioSesion(): void
    }

    class InicioSesion extends EstructuraPanel {
        - serialVersionUID: long

        + InicioSesion()
        - cargarContenido(): void
        - contenidoFooter(): void
        - cargarContenidoRegistro(): void
        - cargarContenidoInicioSesion(): void
    }

    class Registrarse extends EstructuraPanel {
        - serialVersionUID: long
        - campoNombre: JTextField
        - campoUsuario: JTextField
        - campoContraseña: JPasswordField
        - campoConfirmacion: JPasswordField

        + Registrarse()
        - cargarContenido(): void
        - contenidoFooter(): void
        - cargarBotonEntrar(): void
    }

    class VerEjercicios extends EstructuraPanel {
        - serialVersionUID: long
        - ejercicios: ArrayList<Ejercicio>

        + VerEjercicios()
        - contenido(): void
        - contenidoFooter(): void
    }

    class GestionarRutinas extends EstructuraPanel {
        - serialVersionUID: long
        - rutinas: ArrayList<Rutina>
        - listaRutinas: JList<String>
        - scrollPane: JScrollPane

        + GestionarRutinas()
        - contenido(): void
        - llenarLista(): void
        - cargarLista(): void
        - botonGestionarEjerciciosRutina(): void
        - botonEliminarRutina(): void
        - botonAgregarRutina(): void
        - contenidoFooter(): void
    }

    class GestionEjerciciosRutina extends EstructuraPanel {
        - serialVersionUID: long
        - ejercicios: ArrayList<Ejercicio>
        - listaEjercicios: JList<String>
        - scrollPane: JScrollPane
        - comboEjercicios: JComboBox<String>
        - comboMusculos: JComboBox<String
        + GestionEjerciciosRutina(rutina: Rutina)
        - contenido(rutina: Rutina): void
        - cargarLista(): void
        - cargarComboMusculos(): void
        - cargarComboEjercicios(): void
        - llenarLista(rutina: Rutina): void
        - botonAgregarEjercicio(rutina: Rutina): void
        - botonEliminarEjercicio(rutina: Rutina): void
        - actualizarEjercicios(): void
        - cargarLista(): void
        - llenarLista(rutina: Rutina): void
        - contenidoFooter(): void
    }

    class GestionarDatos extends EstructuraPanel {
        - serialVersionUID: long
        - campoNombre: JTextField
        - campoUsuario: JTextField
        - campoClave: JPasswordField

        + GestionarDatos()
        - cargarFunciones(): void
        - cambiarClave(): void
        - cambiarUsuario(): void
        - cambiarNombre(): void
        - confirmar(): boolean
        - cargarContenido(): void
        - contenidoFooter(): void
    }

    class ControlPaneles {
        - panelActual: JPanel

        + ControlPaneles()
        + cambiarPagina(actual: JPanel, siguiente: JPanel): void
    }

    class EstadoSesion {
        - usuario_activo: Usuario_registrado

        + EstadoSesion()
        + getUsuario_activo(): Usuario_registrado
        + setUsuario_activo(usuario_activo: Usuario_registrado): void
    }
}

Usuario_registrado "1" o-- "1..*" Rutina
Rutina "1" o-- "0..*" Ejercicio
Gestor "1" --> "*" Usuario_registrado
Gestor "1" --> "*" Rutina
Gestor "1" --> "*" Ejercicio
ControlPaneles "1" --> "*" EstructuraPanel
ControlPaneles "1" --> "1" JPanel
EstadoSesion "1" --> "1" Usuario_registrado
VentanaPrincipal "1" --> "1" JPanel
GestionarDatos "1" --> "1" Gestor
GestionarDatos "1" --> "1" EstadoSesion
GestionEjerciciosRutina "1" --> "1" Gestor
GestionEjerciciosRutina "1" --> "1" Rutina
GestionarRutinas "1" --> "1" Gestor
GestionarRutinas "1" --> "1" Usuario_registrado
InicioSesion "1" --> "1" Gestor
Registrarse "1" --> "1" Gestor
VerEjercicios "1" --> "1" Gestor

@enduml